// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
    
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCes6CJ0MNC-tisDFNeBCVaxlIO7gzSBks',
    appId: '1:837434895352:web:68583f4147a1466173840d',
    messagingSenderId: '837434895352',
    projectId: 'isearchpfe',
    authDomain: 'isearchpfe.firebaseapp.com',
    storageBucket: 'isearchpfe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOjvqgbfqhlipTTuOqllgokgl4uz3Vvtc',
    appId: '1:837434895352:android:9cd6fb5d5921451173840d',
    messagingSenderId: '837434895352',
    projectId: 'isearchpfe',
    storageBucket: 'isearchpfe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT_9oK_xaGYxSo1O2eSCh7vIZMF10KFrE',
    appId: '1:837434895352:ios:7d08067280abfafd73840d',
    messagingSenderId: '837434895352',
    projectId: 'isearchpfe',
    storageBucket: 'isearchpfe.appspot.com',
    iosClientId: '837434895352-p7kvo787dfrjq5l14hu565aj1e5ntmgr.apps.googleusercontent.com',
    iosBundleId: 'com.example.pfe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT_9oK_xaGYxSo1O2eSCh7vIZMF10KFrE',
    appId: '1:837434895352:ios:7ee864ab2e6f3c9473840d',
    messagingSenderId: '837434895352',
    projectId: 'isearchpfe',
    storageBucket: 'isearchpfe.appspot.com',
    iosClientId: '837434895352-va9mfe03bm9b73b761sdubso0d1um4ab.apps.googleusercontent.com',
    iosBundleId: 'com.example.pfe.RunnerTests',
  );
}
